### ISSUE TITLE
learndrake crashes at model <train_model(data, rec)

### ISSUE THREAD

**Issue by rbhuey** [wlandau/learndrake#7] opened 2019-07-04 22:46 UTC
## Description
learndrake crashes at this step.  Possibly a wrong default setting in R or Rstudio?
Dependency graph is also wrong

 model <- train_model(data, rec)
2019-07-04 22:38:38.444979: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
## Expected output

What output would the correct behavior have produced?

**Comment by wlandau** [comment] 2019-07-04 22:58
Would you help me understand the problem a bit more? Is this where it crashed:

https://github.com/wlandau/learndrake/blob/ece6d41c686bbefbcea8071baf50f43210cd4594/inst/notebooks/2-setup/2-setup.Rmd#L47

Also, how were you accessing the materials? Were you using the [binder resources](https://mybinder.org/v2/gh/wlandau/learndrake/binder?urlpath=rstudio), or were you running stuff locally on your own machine?

**Comment by wlandau** [comment] 2019-07-04 23:04
Just confirmed that `learndrake` does not crash if you launch it through [binder](https://mybinder.org/v2/gh/wlandau/learndrake/binder?urlpath=rstudio)

**Comment by rbhuey** [comment] 2019-07-04 23:15
thanks — testing it now.  
do I need to install remotes,learndrake etc. if I’m launching via binder?

Ray

**Comment by wlandau** [comment] 2019-07-04 23:44
Nope, just click the "launch binder" badge in the REAMDE.

**Comment by rbhuey** [comment] 2019-07-05 00:00
Hi Will,

I did that.  Here is the sequence of steps leading up to the crash at model_16.
I’ve recently been having trouble w/ ggplot2 and vroom, and wonder whether I inadvertently altered default settings in R or Rstudio.

Ray


https://github.com/wlandau/learndrake
launch binder from README

Rstudio opens
File > open project  > learndrake.Rprog          # I assumed this is necessary
 
File > open project > 1-churn.Rprog
File > open File > 1-churn.Rmd

Run all


```{r, output = FALSE}
model_16 <- train_model(data, rec, units1 = 16, units2 = 16)
```
2019-07-04 23:48:50.088244: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA

**Comment by wlandau** [comment] 2019-07-05 00:19
Odd, I followed your steps and cannot reproduce the problem. Closing because I do not think this is an issue in `learndrake` itself, but let's keep the thread open. 

By the way, you do not need to open `learndrake.Rproj` first. I will remove it to reduce confusion.

**Comment by rbhuey** [comment] 2019-07-05 00:24
Thanks Will.   
I will try to figure out how to reset defaults.  I re-downloaded Rstudio and R, but this didn’t help.

Ray

**Comment by wlandau** [comment] 2019-07-05 00:43
Good luck.

The "launch binder" approach should open RStudio in your web browser. No need to download anything.

**Comment by rbhuey** [comment] 2019-07-15 21:52
Hi Will

I figured out the problem.  For some of the exercises I need to re-load library(tensorflow).   I must have missed an instruction to somehow load tensorflow permanently for all of the individual projects.

I’m appending some miscellaneous comments and suggestions — indicating where I had problems with the instructions.  Let me know if you have questions. Incidentally, as will not doubt be obvious, I’m at best an intermediate R user. 

I do like learndrake — I don’t do models like those in the churn study, so the various parts are opaque to me.  Even so, learndrake does give an excellent overview of all the parts. 

Learning to build the parts will be the next step!  And in a real-world project, I run lots of analyses that go nowhere are aren’t interesting.  I might like to keep these, but not in the final plan.

Thanks for your work on drake.  I think this is the approach I need.

Ray

########################
Raymond B. Huey
Professor Emeritus
Department of Biology (Box 351800)
University of Washington
Seattle, WA 9815-1800 USA
hueyrb@uw.edu


SUGGESTIONS/COMMENTS 

##
The text often writes “run make <https://ropensci.github.io/drake/reference/make.html>()” 
	But it should read “run make(plan)”.   Of course the script shows this, but I found “run make()”  initially confusing.


##
several times I needed to reload tensorflow to get an Exercise to work, so it isn’t loading globally.

	library(tensorflow) 

For example, this chunk
```{r, output = FALSE}
model_16 <- train_model(data, rec, units1 = 16, units2 = 16)
```
generates error message:
2019-07-15 19:56:59.553427: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA

but after I load library(tensorflow),  the block runs fine.

###
Exercise 2

“Fill out the [`drake`](http://github.com/ropensci/drake) plan below. The "targets" (`data`, `rec`, etc.) can be in any order.”

Perhaps highlight “FILL OUT”, as I missed this instruction initially. Also, note that the text one needs to fill out this chunk can be extracted from the previous chunk 

###
Exercise 8

Open R/functions.R for editing.

Perhaps might remind the reader that the functions.R script is in 2-setup
###
Exercise 8

Run make() <https://ropensci.github.io/drake/reference/make.html> only (without source("R/functions.R")).

This is unclear.  I would delete “only (without…)” as the previous instruction said to save the file but do not source it.

###
Exercise 9  
I ran these two lines but targets are up to date.  

> source("R/functions.R")
> make(plan)
All targets are already up to date.

###
Exercise 10
took me a minute to find R/plan.R  Perhaps remind reader that this is in the R folder in 3-flow.

###
Exercise 10
 model = train_model(data, rec, act1 = "sigmoid") # edit here
  
Note:  need to add a comma between “sigmoid”), and “#edit here

###
Exercise 10

When I run make(plan) after editing and sourcing plan.R,I get this unexpected message.  From the wording I assumed I should run r_make, but previously I’ve been told to run make.  So this is confusing. The help menu indicates that r_make is more reproducible.

> make(plan)
3 outdated targets:
  conf
  model
  metrics

Please read the "Interactive mode" section of the make() help file.
This prompt only appears once per session.

Really run make() instead of r_make() in interactive mode? 

1: yes
2: no


Selection:

**Comment by wlandau** [comment] 2019-07-17 11:58
Thanks for the detailed feedback! I hope more users provide this kind of review.

**Closed** 2019-07-19 14:28 UTC

**Comment by wlandau** [comment] 2019-07-19 14:30
Ray, I made most of the changes you requested. Please see my responses inline.

> The text often writes “run make <https://ropensci.github.io/drake/reference/make.html>()”
>	But it should read “run make(plan)”.   Of course the script shows this, but I found “run make()”  
> initially confusing.

I went back and fixed the mentions I could find.

> several times I needed to reload tensorflow to get an Exercise to work, so it isn’t loading globally.
>
>	library(tensorflow)
>
> For example, this chunk
> ```{r, output = FALSE}
> model_16 <- train_model(data, rec, units1 = 16, units2 = 16)
> ```
> generates error message:
> 2019-07-15 19:56:59.553427: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
>
> but after I load library(tensorflow),  the block runs fine.

That `tensorflow` message is innocuous. Did your session actually crash?

> “Fill out the [`drake`](http://github.com/ropensci/drake) plan below. The "targets" (`data`, `rec`, etc.) can be in any order.”
>
> Perhaps highlight “FILL OUT”, as I missed this instruction initially. Also, note that the text one needs to fill out this chunk can be extracted from the previous chunk

Sure. I think I addressed this.


> Open R/functions.R for editing.
> 
> Perhaps might remind the reader that the functions.R script is in 2-setup

It should actually be `3-flow/`. I inserted a mention.

> Run make() <https://ropensci.github.io/drake/reference/make.html> only (without source("R/functions.R")).
> 
> This is unclear.  I would delete “only (without…)” as the previous instruction said to save the file but do not source it.

Sure. now fixed.


> I ran these two lines but targets are up to date.
>  source("R/functions.R")
>  make(plan)
> All targets are already up to date.

Perhaps you changed the functions in `2-setup/` instead of `3-flow/`.

>
> took me a minute to find R/plan.R  Perhaps remind reader that this is in the R folder in 3-flow.
>

Sure. Now fixed.

> ###
> Exercise 10
> model = train_model(data, rec, act1 = "sigmoid") # edit here
>
> Note:  need to add a comma between “sigmoid”), and “#edit here

I don't think we need a comma to separate a command from a comment.


> When I run make(plan) after editing and sourcing plan.R,I get this unexpected message.  From the wording I assumed I should run r_make, but previously I’ve been told to run make.  So this is confusing. The help menu indicates that r_make is more reproducible.

At the top of every notebook, there is a command that runs `source("../config/options.R")`, which deactivates all the menus. To make this easier, I also added a `.Rprofile` file, which should hopefully set the options automatically. I do not currently plan to cover `r_make()` in the workshop.
